apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-finquery-conf-pv
  labels:
    app: finquery
    datatype: conf
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath
  hostPath:
    path: /mnt/var/conf/finquery
    type: DirectoryOrCreate
