apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-finquery-conf
spec:
  storageClassName: manual-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: finquery
      datatype: conf